### ISSUE TITLE
uri_for uses die for flow control which interacts badly with eg Plack::Middleware::StackTrace 

### ISSUE THREAD

**Issue by timbunce** [stevan/Path-Router#6]
I was researching a reported [severe slowdown in WebAPI::DBIC](https://github.com/timbunce/WebAPI-DBIC/issues/22). The code was working ok but taking _minutes_ of cpu time to return a response.

It turned out to be a combination of Plack::Middleware::StackTrace setting $SIG{\__DIE__}, Path::Router using exceptions (die) for internal flow control, and WebAPI::DBIC making lots of calls to uri_for that triggered NO MATCH 'exceptions'.

So I'd like to suggest that either `uri_for` not use die for internal flow control, or that it sets `local $SIG{__DIE__};` so the 'exceptions' are immune from interception.

**Comment by stevan** [comment]
Pushed to CPAN, enjoy!
